services:
  localstack:
    image: localstack/localstack:4.14.0
    networks:
      - hmpps
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns

  court-appearance-db:
    image: postgres
    networks:
      - hmpps
    container_name: court-appearance-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=5ch3du13r
      - POSTGRES_USER=court
      - POSTGRES_DB=appearance

networks:
  hmpps:
