integration:
  hmpps-auth:
    url: "https://sign-in.hmpps.service.justice.gov.uk/auth"
  court-register:
    url: "https://court-register-api.hmpps.service.justice.gov.uk"
  manage-users:
    url: "https://manage-users-api.hmpps.service.justice.gov.uk"
  nomis-migration:
    url: "https://prisoner-nomis-migration.hmpps.service.justice.gov.uk"
  prison-register:
    url: "https://prison-register.hmpps.service.justice.gov.uk"
  prisoner-search:
    url: "https://prisoner-search.prison.service.justice.gov.uk"

service:
  active-prisons:
  domain-events:
    poll-interval: PT10s
  ui-base-url: "https://court-appearance-scheduler-ui.hmpps.service.justice.gov.uk"