package uk.gov.justice.digital.hmpps.courtappearanceschedulerapi.access

object Roles {
  val SCHEDULER_UI = "ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER_UI"
  val SCHEDULER_RO = "ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER__RO"
  val SCHEDULER_RW = "ROLE_COURT_APPEARANCES__COURT_APPEARANCE_SCHEDULER__RW"
}
