---
# Per environment values which override defaults in hmpps-court-appearance-scheduler-api/values.yaml

generic-service:

  ingress:
    host: court-appearance-scheduler-api.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: prod
    SENTRY_ENVIRONMENT: prod

  scheduledDowntime:
    enabled: false

generic-prometheus-alerts:
  alertSeverity: move-and-improve-alerts
  rdsAlertsDatabases:
    cloud-platform-0bd73f82c47caa68: "Court Appearance Scheduler API"
  rdsAlertsConnectionThreshold: 100
  sqsOldestAlertQueueNames:
    - "hmpps-court-appearance-scheduler-prod-domain_events_queue"
  sqsAlertsOldestThreshold: 10
  sqsNumberAlertQueueNames:
    - "hmpps-court-appearance-scheduler-prod-domain_events_dlq"
  sqsAlertsTotalMessagesThreshold: 1
  applicationCronJobStatusFailedWindowMinutes: 15
