---
# Per environment values which override defaults in hmpps-court-appearance-scheduler-api/values.yaml

generic-service:

  ingress:
    host: court-appearance-scheduler-api.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: prod
    SENTRY_ENVIRONMENT: prod

  scheduledDowntime:
    enabled: false

  postgresDatabaseRestore:
    enabled: true
    jobName: appearance-scheduler-prod-to-preprod-restore
    # using s3 bucket backup must be after 04:30
    schedule: "30 5 * * *"
    namespace_secrets:
      hmpps-court-appearance-scheduler-postgres:
        DB_HOST: "database_server"
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
      refresh-preprod-postgres:
        DB_HOST_PREPROD: "database_server"
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
      s3-db-restore:
        BUCKET_NAME: "bucket_name"

generic-prometheus-alerts:
  alertSeverity: move-and-improve-alerts
  rdsAlertsDatabases:
    cloud-platform-0bd73f82c47caa68: "Court Appearance Scheduler API"
  rdsAlertsConnectionThreshold: 100
  sqsOldestAlertQueueNames:
    - "hmpps-court-appearance-scheduler-prod-domain_events_queue"
  sqsAlertsOldestThreshold: 10
  sqsNumberAlertQueueNames:
    - "hmpps-court-appearance-scheduler-prod-domain_events_dlq"
  sqsAlertsTotalMessagesThreshold: 1
  applicationCronJobStatusFailedWindowMinutes: 15
