---
# Per environment values which override defaults in hmpps-court-appearance-scheduler-api/values.yaml

generic-service:

  ingress:
    host: court-appearance-scheduler-api-preprod.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: preprod
    SENTRY_ENVIRONMENT: preprod

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: move-and-improve-alerts-non-prod
  rdsAlertsDatabases:
    cloud-platform-fca6318f6d828047: "Court Appearance Scheduler API"
  rdsAlertsConnectionThreshold: 50
  sqsOldestAlertQueueNames:
    - "hmpps-court-appearance-scheduler-preprod-domain_events_queue"
  sqsAlertsOldestThreshold: 10
  sqsNumberAlertQueueNames:
    - "hmpps-court-appearance-scheduler-preprod-domain_events_dlq"
  sqsAlertsTotalMessagesThreshold: 1
  applicationCronJobStatusFailedWindowMinutes: 15
